"use client";

import { CheckCircle2, Download, ExternalLink, Play } from "lucide-react";

export default function VideoResult({ videoUrl, jobId }) {
  const download = () => {
    const anchor = document.createElement("a");
    anchor.href = videoUrl;
    anchor.download = `ayett-stories-${jobId}.mp4`;
    document.body.appendChild(anchor);
    anchor.click();
    anchor.remove();
  };

  return (
    <section className="soft-card animate-rise overflow-hidden rounded-[28px]">
      <div className="flex flex-col gap-4 border-b border-[#e7ebe7] px-5 py-5 sm:flex-row sm:items-center sm:justify-between md:px-7">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-full bg-[#e2f8e9] text-[#1db954]">
            <CheckCircle2 size={21} />
          </div>
          <div>
            <p className="text-base font-black text-[#191414]">Your video is ready</p>
            <p className="text-xs font-semibold text-[#788278]">Generated by Ayett Stories with free local media tools</p>
          </div>
        </div>
        <div className="flex gap-2">
          <a
            href={videoUrl}
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center gap-2 rounded-full border border-[#d8ded8] bg-white px-4 py-2.5 text-xs font-black text-[#4b544b] transition hover:border-[#1db954] hover:text-[#148c42]"
          >
            <ExternalLink size={14} /> Open
          </a>
          <button
            onClick={download}
            className="green-shadow inline-flex items-center gap-2 rounded-full bg-[#1db954] px-4 py-2.5 text-xs font-black text-white transition hover:bg-[#1ed760]"
          >
            <Download size={14} /> Download
          </button>
        </div>
      </div>

      <div className="bg-[#191414] p-2 md:p-3">
        <div className="relative overflow-hidden rounded-2xl bg-black" style={{ aspectRatio: "16 / 9" }}>
          <video src={videoUrl} controls autoPlay className="h-full w-full object-contain" />
        </div>
      </div>

      <div className="flex flex-col gap-1 border-t border-[#e7ebe7] px-5 py-4 text-xs text-[#7c867c] sm:flex-row sm:items-center sm:justify-between md:px-7">
        <span className="font-mono">Job {jobId}</span>
        <span className="flex items-center gap-1.5 font-semibold"><Play size={12} fill="currentColor" className="text-[#1db954]" /> Local MP4 · no paid video API</span>
      </div>
    </section>
  );
}
